services:
  ssh-server-2:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: ssh-server-2
    networks:
      mynetwork:
        ipv4_address: 172.28.0.2
    ports:
      - "2222:22"
    restart: always

  ssh-server-3:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: ssh-server-3
    networks:
      mynetwork:
        ipv4_address: 172.28.0.3
    ports:
      - "2223:22"
    restart: always

  ssh-server-4:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: ssh-server-4
    networks:
      mynetwork:
        ipv4_address: 172.28.0.4
    ports:
      - "2224:22"
    restart: always

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: "172.28.0.0/16"
