---
- hosts: all
  become: true
  tasks:

  - name: install Apache
    package:
      name: 
        - "{{ apache_package }}"
      state: latest
      update_cache: yes

  - name: run Apache
    command: apache2ctl start

