---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache
    apt:
      name:
        - apache2
